apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: crud
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-pod
        image: mysql/mysql-server:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-initdb-config
              key: mysql_db
        - name: MYSQL_ROOT_PASSWORD
          value: mauFJcuf5dhRMQrjj
        - name: MYSQL_ROOT_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-initdb-config
              key: mysql_host
        volumeMounts:
          - mountPath: /docker-entrypoint-initdb.d
            name: mysql-initdb
          - mountPath: /var/lib/mysql
            name: mysql-data

      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-pvc
